# Generated by Django 2.2 on 2020-05-16 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_category_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='meta_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_keywords',
            field=models.TextField(default=''),
        ),
    ]
